pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenLocal()
	}
}

rootProject.name = "retrofabric-api"

include("retrofabric-core")
include("retrofabric-logger-api-v1")
include("retrofabric-mod-menu-v1")
include("retrofabric-registry-v1")
include("retrofabric-loot-v1")
include("retrofabric-recipe-v1")
include("retrofabric-biome-v1")
include("retrofabric-crash-report-info-v1")
include("retrofabric-entity-events-v1")
include("retrofabric-gamerule-api-v1")
include("retrofabric-item-groups-v0")
include("retrofabric-keybinding-api-v1")
include("retrofabric-lifecycle-events-v1")
include("retrofabric-rendering-api-v1")
include("retrofabric-resource-loader-v1")
include("retrofabric-networking-api-v1")
include("retrofabric-permissions-api-v1")
include("retrofabric-sponge-command-api-v2")
include("retrofabric-vanilla-command-api-v1")
