[versions]
retrofabric-base = "2.0.0-retrofabric.1"
mc = "1.7.10"
yarn = "202204202025"
loader = "0.13.3"
loom = "0.12.27"
guava = "31.1-jre"
checkstyle = "10.12.5"
grgit = "5.2.1"

[libraries]
yarn-mappings = { module = "net.fabricmc:yarn", version = "1.7.10+build.202204202025:v2" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
# Logger sudah di-fork internal: :retrofabric-logger-api-v1 (id.retrofabric.api.logger.v1)

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
